<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1391164835062" stop="1391164835384">
    <name>my.company.ManyInfoTest</name>
    <description type="text">Testsuite has testcases with many steps
    and
many lines in description</description>
    <test-cases>
        <test-case start="1391164835062" stop="1391164835075" status="failed" severity="critical">
            <name>attachmentsTest</name>
            <description type="text">Single-line description</description>
            <failure>
                <message>AssertionError: This test should be failed</message>
                <stack-trace>java.lang.AssertionError: This test should be failed
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at my.company.steps.CommonSteps.makeThisTestFailed(CommonSteps.java:35)
	at my.company.ManyInfoTest.attachmentsTest(ManyInfoTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
</stack-trace>
            </failure>
            <steps>
                <step start="1391164835073" stop="1391164835075" status="failed">
                    <name>makeThisTestFailed</name>
                    <title>Make this test failed</title>
                    <attachments>
                        <attachment title="TXT Attachment" source="eefd7176-26bf-4d34-83f8-0dc90740f310-attachment.txt" type="txt"/>
                    </attachments>
                </step>
            </steps>
            <attachments>
                <attachment title="JSON Attachment" source="1b942a82-8043-40fd-8a79-eff1a1fb8712-attachment.json" type="json"/>
                <attachment title="XML Attachment" source="a761b99a-4589-4439-942f-29da851ea259-attachment.xml" type="xml"/>
                <attachment title="JPG Attachment" source="9f0aacec-b46c-4132-bd54-6df3c8116788-attachment.jpg" type="jpg"/>
            </attachments>
            <labels>
                <label name="story" value="OtherScreenshot"/>
                <label name="feature" value="Screenshot"/>
            </labels>
        </test-case>
        <test-case start="1391164835062" stop="1391164835066" status="broken" severity="blocker">
            <name>lotOfStepsTest</name>
            <description type="text">I have many steps 

    Parent Step 
    Last 
    MakeThisTestBroken</description>
            <failure>
                <message>FileNotFoundException: No file found.</message>
                <stack-trace>java.io.FileNotFoundException: No file found.
	at my.company.steps.CommonSteps.makeThisTestBroken(CommonSteps.java:29)
	at my.company.ManyInfoTest.lotOfStepsTest(ManyInfoTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
</stack-trace>
            </failure>
            <steps>
                <step start="1391164835063" stop="1391164835064" status="passed">
                    <name>parentStep</name>
                    <title>Parent step</title>
                    <steps>
                        <step start="1391164835064" stop="1391164835064" status="passed">
                            <name>step</name>
                            <title>&quot;First nested&quot; step</title>
                        </step>
                        <step start="1391164835064" stop="1391164835064" status="passed">
                            <name>step</name>
                            <title>&quot;Second nested&quot; step</title>
                        </step>
                        <step start="1391164835064" stop="1391164835064" status="passed">
                            <name>step</name>
                            <title>&quot;Third nested&quot; step</title>
                        </step>
                    </steps>
                </step>
                <step start="1391164835064" stop="1391164835064" status="passed">
                    <name>step</name>
                    <title>&quot;Last&quot; step</title>
                </step>
                <step start="1391164835065" stop="1391164835065" status="broken">
                    <name>makeThisTestBroken</name>
                    <title>Make this test broken</title>
                </step>
            </steps>
            <attachments/>
            <labels/>
        </test-case>
        <test-case start="1391164835063" stop="1391164835065" status="failed" severity="normal">
            <name>longAssertionTest</name>
            <title>Test with long assertion text</title>
            <failure>
                <message>AssertionError: 
Expected: &quot;{\n\&quot;name\&quot;: \&quot;test\&quot;,\n\&quot;value\&quot;: \&quot;ok value\&quot;\n}&quot;
     but: was &quot;{\n\&quot;name\&quot;: \&quot;test\&quot;,\n\&quot;value\&quot;: \&quot;bad value\&quot;\n}&quot;</message>
                <stack-trace>java.lang.AssertionError: 
Expected: &quot;{\n\&quot;name\&quot;: \&quot;test\&quot;,\n\&quot;value\&quot;: \&quot;ok value\&quot;\n}&quot;
     but: was &quot;{\n\&quot;name\&quot;: \&quot;test\&quot;,\n\&quot;value\&quot;: \&quot;bad value\&quot;\n}&quot;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at my.company.ManyInfoTest.longAssertionTest(ManyInfoTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels/>
            <parameters>
                <parameter name="PATH" value="/home/just-boris/.rvm/gems/ruby-2.0.0-p353/bin:/home/just-boris/.rvm/gems/ruby-2.0.0-p353@global/bin:/home/just-boris/.rvm/rubies/ruby-2.0.0-p353/bin:/home/just-boris/.rvm/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games" kind="environment-variable"/>
                <parameter name="BASEDIR" value="/home/just-boris/coding/allure-junit-variant" kind="environment-variable"/>
                <parameter name="OS_NAME" value="Linux" kind="environment-variable"/>
                <parameter name="OS_VERSION" value="3.11.0-15-generic" kind="environment-variable"/>
                <parameter name="JAVA_VERSION" value="1.7.0_45" kind="environment-variable"/>
            </parameters>
        </test-case>
    </test-cases>
    <labels/>
</ns2:test-suite>
